version: 0.2

phases:
  build:
    commands:
      - aws configure set default.region ap-northeast-2
      - CFT=$(cat CloudFormationTest.yaml)
      - aws cloudformation create-change-set  --stack-name yhwStack --template-body "$CFT"
      
