version: 0.2

phases:
  pre_build:
    commands:
        - aws configure set default.region ap-northeast-2
        - aws cloudformation delete-stack --stack-name yhwStack

  build:
    commands:
      - CFT=$(cat CloudFormationTest.yaml)
      - aws cloudformation create-stack --template-body "$CFT" --stack-name yhwStack
      
