version: 0.2

phases:
  pre_build:
    commands:
      - aws configure set default.region ap-northeast-2

  build:
    commands:
      - aws cloudformation deploy --no-fail-on-empty-changeset --stack-name yhwStack --template-file CloudFormationTest.yaml