version: 0.2

phases:
  pre_build:
    commands:
      - aws configure set default.region ap-northeast-2
      - aws cloudformation delete-change-set --stack-name yhwStack --change-set-name yhwStackChangeSet

  build:
    commands:
      - CFT=$(cat CloudFormationTest.yaml)
      - aws cloudformation create-change-set --stack-name yhwStack --template-body "$CFT" --change-set-name yhwStackChangeSet
      - aws cloudformation execute-change-set --stack-name yhwStack --change-set-name yhwStackChangeSet
      
