AWSTemplateFormatVersion: '2010-09-09'

Description: 'CI/CD for CloudFormation Example'

Resources:
  MyLambdaTest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: s3://msi-test-yhw/lam.zip
      Runtime: python3.6


