AWSTemplateFormatVersion: '2010-09-09'

Description: 'CI/CD for CloudFormation Example'

Resources:
  WebServerInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0fd0765afb77bcca7'
      InstanceType: 't3.small'
      SecurityGroupIds: 
        - !Ref WebServerSecurityGroup
      KeyName: yhw-key
      Tags:
        - Key: Name
          Value: IU
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config 
          systemctl restart sshd
          echo 'password' | passwd --stdin ec2-user
          yum -y install httpd
          systemctl start httpd
      

  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Test'
      GroupName: testGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  
